[package]

name = "cam"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "eddyb"
]
tags = []

[lib]

name = "cam"
path = "src/lib.rs"

[dependencies.vecmath]

git = "https://github.com/pistondevelopers/vecmath"

[dependencies.input]

git = "https://github.com/pistondevelopers/input"

